name: "Duplicate Job Names"

on:
  push:

jobs:
  first:
    name: "duplicate"
    runs-on: ubuntu-22.04
    steps:
      - run: |
          echo "Random number: ${RANDOM}"
  second:
    name: "duplicate"
    runs-on: ubuntu-22.04
    steps:
      - run: |
          echo "Random number: ${RANDOM}"
